name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn install --frozen-lockfile
    - name: Test tsc
      run: |
        yarn tsc
        yarn start-ts
    - name: Test Webpack
      run: |
        yarn webpack
        yarn start-webpack
    - name: Test ts-node
      run: yarn start-ts-node
    - name: Test ts-jest
      # For now, "yarn test-ts" emits "ReferenceError: exports is not defined" error.
      run: |
        yarn test-ts src/square.test.ts
        yarn test-ts src/square42.test.ts
    - name: Test babel-jest
      run: yarn test-babel
